### ISSUE TITLE
Installs on iOS, but entering and submitting chat text kills app

### ISSUE THREAD

**Issue by davenotik** [flutter/firechat-flutter#14]
I can't get the chat text to show in the chat view – instead, when I enter chat text and tap send, it crashes. I had done a `flutter upgrade` and a `flutter ios --init`.

**Comment by chinmaygarde** [comment]
`flutter ios --init` is no longer present in the latest versions of Flutter. That command is now implicitly run when you try to start the application. So I am suspicious that you are not running the latest version. Can you `git log` in your `flutter` repo to make sure.

**Comment by davenotik** [comment]
`git log` showed latest update on 2/14, so I did a `flutter upgrade` in my flutter dir (had to first stash the /ios files) and now I'm up to date. I'll test on my device, but even in the simulator the keyboard doesn't come up and when I send a message it doesn't show: http://d.pr/i/1h3Mv

**Comment by davenotik** [comment]
Ok, doesn't crash on device now, but (same as simulator) it doesn't do anything when I send the message. The keyboard does slide up though on the device.

**Comment by davenotik** [comment]
And actually it still does crash. Sometimes it doesn't and I can enter and submit text, and other times it does.

**Comment by davenotik** [comment]
Is this supposed to be working better on iOS? Should the text be showing?

**Comment by davenotik** [comment]
Update?

**Comment by eseidelGoogle** [comment]
So the simulator should be fully supported for this app.  I'll see if I can repro just now.  cc @collinjackson, @tvolkert @chinmaygarde

**Comment by collinjackson** [comment]
works fine on the simulator for me. make sure you're testing step_3, step_4, or step_5 since rendering messages isn't implemented until step_3.

This is my step_5:
![screen shot 2016-03-16 at 12 43 17 pm](https://cloud.githubusercontent.com/assets/394889/13826421/aea93418-eb74-11e5-8f6d-f926a687c91f.png)

**Comment by collinjackson** [comment]
I would recommend these settings in the Hardware > Keyboard menu of the simulator: 
![screen shot 2016-03-16 at 12 46 12 pm](https://cloud.githubusercontent.com/assets/394889/13826501/307d01cc-eb75-11e5-9e12-d863a1be50df.png)

**Comment by collinjackson** [comment]
It works for me on my physical device as well.

![img_4387](https://cloud.githubusercontent.com/assets/394889/13826876/f19210ae-eb76-11e5-9321-609a3326d69e.PNG)

**Comment by davenotik** [comment]
I'm testing step_6 in fact. What about you @collinjackson?

The original issue here – that typing would cause a crash – has since been resolved.

The issues now:

[ ] The chat messages don't show when running my hardware (iPhone 6S, iOS 9.2.1). Though it seems it does for you.
[ ] The software keyboard doesn't come up in the simulator when in the text field. Is it supposed to? No biggie, just mentioning that too. I do have those same settings in Hardware > Keyboard.

**Comment by collinjackson** [comment]
steps_5+ use Firebase and won't work on device until #28 is fixed. please use step_4.

You can toggle the software keyboard with ⌘-K. It should look like this:

![image](https://cloud.githubusercontent.com/assets/394889/13827597/c58c894a-eb7a-11e5-9842-70161f4aa220.png)

**Comment by davenotik** [comment]
Got it. I'll follow that issue, and close this one as the original issue here – crashing when typing – seems to longer be the case in successive updates.

**Comment by davenotik** [comment]
FYI, yes step_4 shows messages, but of course as you just acknowledged in #28, step_5+ is where it starts using Firebase and where the issue is with messages not showing on the device.
