### ISSUE TITLE
Which platforms does this support?

### ISSUE THREAD

**Issue by davenotik** [flutter/firechat-flutter#2]
Still wrapping my head around Flutter. AFAIK this code would work with both Android and iOS as/if supported by Flutter?

**Comment by abarth** [comment]
Yes, that's the idea.

**Comment by collinjackson** [comment]
Yes

**Comment by davenotik** [comment]
I noticed there's a run-around to get it going for iOS, according to the README. Is that still true?

**Comment by collinjackson** [comment]
It should work out of the box on iOS now.
